
ALTER TABLE public.memories
  ADD COLUMN IF NOT EXISTS attachment_url TEXT,
  ADD COLUMN IF NOT EXISTS comment TEXT,
  ADD COLUMN IF NOT EXISTS ingredients TEXT,
  ADD COLUMN IF NOT EXISTS steps TEXT,
  ADD COLUMN IF NOT EXISTS servings INTEGER,
  ADD COLUMN IF NOT EXISTS time_minutes INTEGER,
  ADD COLUMN IF NOT EXISTS travel_kind TEXT,
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS rating INTEGER,
  ADD COLUMN IF NOT EXISTS price_range TEXT,
  ADD COLUMN IF NOT EXISTS maps_url TEXT,
  ADD COLUMN IF NOT EXISTS weekdays INTEGER[],
  ADD COLUMN IF NOT EXISTS routine_time TEXT,
  ADD COLUMN IF NOT EXISTS linked_recurrence_id UUID;
